서울시 공영주차장 안내 정보
https://data.seoul.go.kr/dataList/OA-13122/S/1/datasetView.do
- 컬럼 수가 많아서 필요한 컬럼만 골라 사용하면 될 것 같음
- 위도, 경도 컬럼의 NULL값 842개
    - 사용한다면 삭제보단 방법을 찾아서 값을 채우는 것이 좋을 듯(GPT는 지오코딩을 알려주네요)

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import warnings

In [4]:
parking_df = pd.read_csv('C:/Users/USER/OneDrive/바탕 화면/Final_project/서울시 공영주차장 안내 정보.csv', encoding='cp949')
parking_df.head()

,주차장코드,주차장명,주소,주차장 종류,주차장 종류명,운영구분,운영구분명,전화번호,주차현황 정보 제공여부,주차현황 정보 제공여부명,...,기본 주차 시간(분 단위),추가 단위 요금,추가 단위 시간(분 단위),버스 기본 주차 요금,버스 기본 주차 시간(분 단위),버스 추가 단위 시간(분 단위),버스 추가 단위 요금,일 최대 요금,위도,경도
0,1010089,초안산근린공원주차장(구),도봉구 창동 24-0,NW,노외 주차장,1,시간제 주차장,NaN,0,미연계중,...,NaN,300.0,10.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
1,1012254,마들스타디움(근린공원)(구),노원구 상계동 770-2,NW,노외 주차장,1,시간제 주차장,02-2289-6735,0,미연계중,...,5.0,150.0,5.0,0.0,0.0,0.0,0.0,11000.0,NaN,NaN
2,1013181,마장동(건물) 공영주차장(구),성동구 마장동 463-2,NW,노외 주차장,1,시간제 주차장,02-2204-7970,3,120~2일이내 연계데이터 존재(통신점검중),...,5.0,50.0,5.0,0.0,0.0,0.0,0.0,NaN,37.569939,127.035145
3,1025695,영등포여고 공영(구),영등포구 신길동 184-3,NW,노외 주차장,1,시간제 주차장,02-2677-1401,1,현재~20분이내 연계데이터 존재(현재 주차대수 표현),...,5.0,50.0,5.0,0.0,0.0,0.0,0.0,0.0,37.515205,126.915116
4,1025696,당산근린공원 공영(구),영등포구 당산동3가 385-0,NW,노외 주차장,1,시간제 주차장,02-2677-1401,1,현재~20분이내 연계데이터 존재(현재 주차대수 표현),...,5.0,150.0,5.0,0.0,0.0,0.0,0.0,0.0,37.525526,126.895794

In [6]:
parking_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18767 entries, 0 to 18766
Data columns (total 39 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   주차장코드              18767 non-null  int64
 1   주차장명               18767 non-null  object
 2   주소                 18767 non-null  object
 3   주차장 종류             18767 non-null  object
 4   주차장 종류명            18767 non-null  object
 5   운영구분               18767 non-null  int64
 6   운영구분명              18767 non-null  object
 7   전화번호               9787 non-null   object
 8   주차현황 정보 제공여부       18767 non-null  int64
 9   주차현황 정보 제공여부명      18767 non-null  object
 10  총 주자면              18588 non-null  float64
 11  유무료구분              18767 non-null  object
 12  유무료구분명             18767 non-null  object
 13  야간무료개방여부           18767 non-null  object
 14  야간무료개방여부명          18767 non-null  object
 15  평일 운영 시작시각(HHMM)   18767 non-null  int64
 16  평일 운영 종료시각(HHMM)   18767 non-null  int64
 17  주말 운영 시작시각(HHMM)   18767 non-null  int64
 18  주말 운영 종료시각(HHMM)   18767 non-null  int64
 19  공휴일 운영 시작시각(HHMM)  18767 non-null  int64
 20  공휴일 운영 종료시각(HHMM)  18767 non-null  int64
 21  최종데이터 동기화 시간       18767 non-null  object
 22  토요일 유,무료 구분        18767 non-null  object
 23  토요일 유,무료 구분명       18767 non-null  object
 24  공휴일 유,무료 구분        18767 non-null  object
 25  공휴일 유,무료 구분명       18767 non-null  object
 26  월 정기권 금액           15906 non-null  float64
 27  노상 주차장 관리그룹번호      17838 non-null  float64
 28  기본 주차 요금           18548 non-null  float64
 29  기본 주차 시간(분 단위)     18547 non-null  float64
 30  추가 단위 요금           16919 non-null  float64
 31  추가 단위 시간(분 단위)     16918 non-null  float64
 32  버스 기본 주차 요금        18165 non-null  float64
 33  버스 기본 주차 시간(분 단위)  18165 non-null  float64
 34  버스 추가 단위 시간(분 단위)  18164 non-null  float64
 35  버스 추가 단위 요금        18164 non-null  float64
 36  일 최대 요금            15596 non-null  float64
 37  위도                 17925 non-null  float64
 38  경도                 17925 non-null  float64
dtypes: float64(14), int64(9), object(16)
memory usage: 5.6+ MB

In [9]:
parking_df.isnull().sum()

주차장코드                   0
주차장명                    0
주소                      0
주차장 종류                  0
주차장 종류명                 0
운영구분                    0
운영구분명                   0
전화번호                 8980
주차현황 정보 제공여부            0
주차현황 정보 제공여부명           0
총 주자면                 179
유무료구분                   0
유무료구분명                  0
야간무료개방여부                0
야간무료개방여부명               0
평일 운영 시작시각(HHMM)        0
평일 운영 종료시각(HHMM)        0
주말 운영 시작시각(HHMM)        0
주말 운영 종료시각(HHMM)        0
공휴일 운영 시작시각(HHMM)       0
공휴일 운영 종료시각(HHMM)       0
최종데이터 동기화 시간            0
토요일 유,무료 구분             0
토요일 유,무료 구분명            0
공휴일 유,무료 구분             0
공휴일 유,무료 구분명            0
월 정기권 금액             2861
노상 주차장 관리그룹번호         929
기본 주차 요금              219
기본 주차 시간(분 단위)        220
추가 단위 요금             1848
추가 단위 시간(분 단위)       1849
버스 기본 주차 요금           602
버스 기본 주차 시간(분 단위)     602
버스 추가 단위 시간(분 단위)     603
버스 추가 단위 요금           603
일 최대 요금              3171
위도                    842
경도                    842
dtype: int64

In [10]:
#컬럼수가 많아서 20~마지막 부분 따로 확인
parking_df.iloc[:, 19:].isnull().sum()

공휴일 운영 시작시각(HHMM)       0
공휴일 운영 종료시각(HHMM)       0
최종데이터 동기화 시간            0
토요일 유,무료 구분             0
토요일 유,무료 구분명            0
공휴일 유,무료 구분             0
공휴일 유,무료 구분명            0
월 정기권 금액             2861
노상 주차장 관리그룹번호         929
기본 주차 요금              219
기본 주차 시간(분 단위)        220
추가 단위 요금             1848
추가 단위 시간(분 단위)       1849
버스 기본 주차 요금           602
버스 기본 주차 시간(분 단위)     602
버스 추가 단위 시간(분 단위)     603
버스 추가 단위 요금           603
일 최대 요금              3171
위도                    842
경도                    842
dtype: int64